apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: training-app-environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - autoSync: 'true'
        environment: dev
        revision: main
      - autoSync: 'true'
        environment: staging
        revision: main
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      labels:
        environment: '{{environment}}'
        managed-by: applicationset
      name: training-app-{{environment}}
      namespace: argocd
    spec:
      destination:
        namespace: devops-training
        server: https://kubernetes.default.svc
      project: devops-training
      source:
        path: k8s/overlays/{{environment}}
        repoURL: https://github.com/rohandeb2/k8s_argocd_project.git
        targetRevision: '{{revision}}'
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
          limit: 3
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
