apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
spec:
  project: devops-training
  source:
    repoURL: https://github.com/rohandeb2/k8s_argocd_project.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-training-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/updateStrategy/rollingUpdate/partition
  revisionHistoryLimit: 20
