apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: training-app-high
  annotations:
    argocd.argoproj.io/sync-wave: "-3"        
value: 1000
globalDefault: false
preemptionPolicy: PreemptLowerPriority        
description: >
  High priority — used by prod/staging pods.
  These pods will evict dev-priority pods if the node runs out of resources.


---


apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: training-app-low
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
value: 100
globalDefault: false
preemptionPolicy: Never                       
description: >
  Low priority — used by dev pods.
  Evicted first when the node is under memory/CPU pressure.
