apiVersion: v1
kind: Secret
metadata:
  name: training-app-secret
  namespace: devops-training
  labels:
    app: training-app
type: Opaque
stringData:
  DB_PASSWORD: "change the value"
  API_KEY: "change the value"
