apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-app-sa
  namespace: devops-training
  labels:
    app: training-app
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: training-app-role
  namespace: devops-training
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: training-app-rolebinding
  namespace: devops-training
subjects:
  - kind: ServiceAccount
    name: training-app-sa
    namespace: devops-training
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: training-app-role
