apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-training-dev
resources:
  - ../../base
images:
  - name: training-app
    newName: rohan700/training-app
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: training-app
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler
      name: training-app-hpa
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: training-app
configMapGenerator:
  - name: training-app-config
    behavior: merge
    literals:
      - APP_VERSION=v1.0.0-dev
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
generatorOptions:
  disableNameSuffixHash: true
